export enum ActionType {
    GETALLPOST = "GET_ALL_POST_SUCCESS",
    POSTPENDING = "GET_ALL_POST_PENDING",
    POSTERR = "GET_ALL_POST_FAILURE",
    POST_DATA_REQUEST= "POST_DATA_REQUEST",
    POST_DATA_SUCCESS= "POST_DATA_SUCCESS",
    POST_DATA_FAILURE= "POST_DATA_FAILURE"
}